import { BASE_URL, BASE_API_URL } from '../config/env';

export { BASE_URL, BASE_API_URL };

export const API_URLS = {
  auth: {
    login: `${BASE_API_URL}/auth/login`,
    logout: `${BASE_API_URL}/auth/logout`,
    me: `${BASE_API_URL}/auth/me`,
    register: `${BASE_API_URL}/auth/register`,
  },
  users: {
    all: `${BASE_API_URL}/users/`,
    create: `${BASE_API_URL}/users/`,
    byId: (id) => `${BASE_API_URL}/users/${id}`,
    edit: (id) => `${BASE_API_URL}/users/${id}`,
    delete: (id) => `${BASE_API_URL}/users/${id}`,
  },
  zones: {
    all: `${BASE_API_URL}/zones/`,
    byId: (id) => `${BASE_API_URL}/zones/${id}`,
    create: `${BASE_API_URL}/zones/`,
    edit: (id) => `${BASE_API_URL}/zones/${id}`,
    delete: (id) => `${BASE_API_URL}/zones/${id}`,
    devices: (id) => `${BASE_API_URL}/zones/${id}/devices`,
  },
  devices: {
    all: `${BASE_API_URL}/devices/`,
    byId: (id) => `${BASE_API_URL}/devices/${id}`,
    create: `${BASE_API_URL}/devices/`,
    edit: (id) => `${BASE_API_URL}/devices/${id}`,
    delete: (id) => `${BASE_API_URL}/devices/${id}`,
  },
  sensors: {
    all: `${BASE_API_URL}/sensors/`,
    byId: (id) => `${BASE_API_URL}/sensors/${id}`,
    create: `${BASE_API_URL}/sensors/`,
    edit: (id) => `${BASE_API_URL}/sensors/${id}`,
    delete: (id) => `${BASE_API_URL}/sensors/${id}`,
    updateStatus: (id) => `${BASE_API_URL}/sensors/${id}/status`,
  },
  employees: {
    all: `${BASE_API_URL}/employees/`,
    byId: (id) => `${BASE_API_URL}/employees/${id}`,
    create: `${BASE_API_URL}/employees/`,
    edit: (id) => `${BASE_API_URL}/employees/${id}`,
    delete: (id) => `${BASE_API_URL}/employees/${id}`,
    byZone: (zoneId) => `${BASE_API_URL}/employees/by-zone/${zoneId}`,
  },
  observations: {
    all: `${BASE_API_URL}/observations`,
    byId: (id) => `${BASE_API_URL}/observations/${id}`,
    create: `${BASE_API_URL}/observations`,
    update: (id) => `${BASE_API_URL}/observations/${id}`,
    delete: (id) => `${BASE_API_URL}/observations/${id}`,
    addImage: (id) => `${BASE_API_URL}/observations/${id}/images`,
    countByAgent: (agentId) => `${BASE_API_URL}/observations/agent/${agentId}/count`,
  },
  incidentEvents: {
    all: `${BASE_API_URL}/incidentEvents/`,
    byId: (id) => `${BASE_API_URL}/incidentEvents/${id}`,
    update: (id) => `${BASE_API_URL}/incidentEvents/${id}`,
    resolve: (id) => `${BASE_API_URL}/incidentEvents/${id}/resolve`,
  },
  audits: {
    all: `${BASE_API_URL}/audits/`,
    byId: (id) => `${BASE_API_URL}/audits/${id}`,
    create: `${BASE_API_URL}/audits/`,
    edit: (id) => `${BASE_API_URL}/audits/${id}`,
    delete: (id) => `${BASE_API_URL}/audits/${id}`,
    addFinding: (id) => `${BASE_API_URL}/audits/${id}/findings`,
    updateFinding: (id, fid) => `${BASE_API_URL}/audits/${id}/findings/${fid}`,
    deleteFinding: (id, fid) => `${BASE_API_URL}/audits/${id}/findings/${fid}`,
  },
  trainings: {
    all: `${BASE_API_URL}/trainings/`,
    byId: (id) => `${BASE_API_URL}/trainings/${id}`,
    create: `${BASE_API_URL}/trainings/`,
    edit: (id) => `${BASE_API_URL}/trainings/${id}`,
    delete: (id) => `${BASE_API_URL}/trainings/${id}`,
    addParticipant: (id) => `${BASE_API_URL}/trainings/${id}/participants`,
  },
  alerts: {
    all: `${BASE_API_URL}/alerts/`,
    byId: (id) => `${BASE_API_URL}/alerts/${id}`,
    markRead: (id) => `${BASE_API_URL}/alerts/${id}/read`,
    acknowledge: (id) => `${BASE_API_URL}/alerts/${id}/acknowledge`,
    resolve: (id) => `${BASE_API_URL}/alerts/${id}/resolve`,
    delete: (id) => `${BASE_API_URL}/alerts/${id}`,
  },
  notifications: {
    all: `${BASE_API_URL}/notifications/`,
    byId: (id) => `${BASE_API_URL}/notifications/${id}`,
    dispatch: `${BASE_API_URL}/notifications/dispatch`,
  },
  userNotifications: {
    all: `${BASE_API_URL}/user-notifications/`,
    unreadCount: `${BASE_API_URL}/user-notifications/unread-count`,
    markAsRead: (id) => `${BASE_API_URL}/user-notifications/${id}/read`,
    markAllAsRead: `${BASE_API_URL}/user-notifications/read-all`,
  },
  reports: {
    all: `${BASE_API_URL}/reports`,
    byId: (id) => `${BASE_API_URL}/reports/${id}`,
    create: `${BASE_API_URL}/reports`,
    update: (id) => `${BASE_API_URL}/reports/${id}`,
    delete: (id) => `${BASE_API_URL}/reports/${id}`,
  },
  readings: {
    all: `${BASE_API_URL}/readings`,
    byId: (id) => `${BASE_API_URL}/readings/${id}`,
    latestByDevice: (deviceId) => `${BASE_API_URL}/readings/latest/device/${deviceId}`,
    historyByDevice: (deviceId) => `${BASE_API_URL}/readings/history/device/${deviceId}`,
    latestByZone: (zoneId) => `${BASE_API_URL}/readings/latest/zone/${zoneId}`,
  },
  sensorData: {
    all: `${BASE_API_URL}/sensor-data/`,
    latest: `${BASE_API_URL}/sensor-data/latest`,
    stats: `${BASE_API_URL}/sensor-data/stats`,
  },
  companies: {
    all: `${BASE_API_URL}/companies/`,
    byId: (id) => `${BASE_API_URL}/companies/${id}`,
    create: `${BASE_API_URL}/companies/`,
  },
};
